USE [master]
GO

/****** Object:  Database [Noticias]    Script Date: 12/12/2017 8:42:58 ******/
CREATE DATABASE [Noticias]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Noticias', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Noticias.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Noticias_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Noticias_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Noticias] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Noticias].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Noticias] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Noticias] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Noticias] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Noticias] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Noticias] SET ARITHABORT OFF 
GO

ALTER DATABASE [Noticias] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Noticias] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Noticias] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Noticias] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Noticias] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Noticias] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Noticias] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Noticias] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Noticias] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Noticias] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Noticias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Noticias] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Noticias] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Noticias] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Noticias] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Noticias] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Noticias] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Noticias] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Noticias] SET  MULTI_USER 
GO

ALTER DATABASE [Noticias] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Noticias] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Noticias] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Noticias] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Noticias] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Noticias] SET QUERY_STORE = OFF
GO

USE [Noticias]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Noticias] SET  READ_WRITE 
GO


